name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: archlinux-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install TypeScript compiler
        run: pacman -Syu typescript --noconfirm
      - name: Compile TypeScript to JavaScript
        run: tsc index.ts
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: .
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
